# Generated by Django 6.0.4 on 2026-04-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('phoneno', models.CharField(max_length=15)),
                ('reg_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
